### PR TITLE
add dependency on ros-noetic-tf (#10)

### PR DESCRIPTION
**Pull request by mjcarroll**
To allow bridging tf/tfMessage out of the box

Forward port of #10, adjusted for Foxy/Noetic.

### CODE REVIEW

**Review by mikaelarguedas — APPROVED** [review]
lgtm :+1:

**Review by jacobperron — APPROVED** [review]

**Comment by mikaelarguedas** [comment]
I am having second thoughts about that forward port.
This actually brings a lot of dependencies in foxy/noetic.
In previous distros we didnt see the difference but in noetic all of ros-core has been trimmed by removing the unnecessary boost dependencies.

As tf depends on tf2-ros -> that depends on actionlib -> that depends on libboost-all, this single added dependency brings in around 380MB of extra stuff:

```
The following additional packages will be installed:
  autoconf automake autotools-dev cpp-8 fontconfig fontconfig-config fonts-dejavu-core fonts-liberation gcc-8 gfortran gfortran-8 gfortran-9 graphviz ibverbs-providers libann0 libboost-all-dev
  libboost-atomic-dev libboost-container-dev libboost-container1.71-dev libboost-container1.71.0 libboost-context-dev libboost-context1.71-dev libboost-context1.71.0 libboost-coroutine-dev
  libboost-coroutine1.71-dev libboost-coroutine1.71.0 libboost-exception-dev libboost-exception1.71-dev libboost-fiber-dev libboost-fiber1.71-dev libboost-fiber1.71.0 libboost-graph-dev
  libboost-graph-parallel-dev libboost-graph-parallel1.71-dev libboost-graph-parallel1.71.0 libboost-graph1.71-dev libboost-graph1.71.0 libboost-iostreams-dev libboost-iostreams1.71-dev
  libboost-iostreams1.71.0 libboost-locale-dev libboost-locale1.71-dev libboost-locale1.71.0 libboost-log-dev libboost-log1.71-dev libboost-log1.71.0 libboost-math-dev libboost-math1.71-dev libboost-math1.71.0
  libboost-mpi-dev libboost-mpi-python-dev libboost-mpi-python1.71-dev libboost-mpi-python1.71.0 libboost-mpi1.71-dev libboost-mpi1.71.0 libboost-numpy-dev libboost-numpy1.71-dev libboost-numpy1.71.0
  libboost-python-dev libboost-python1.71-dev libboost-python1.71.0 libboost-random-dev libboost-random1.71-dev libboost-random1.71.0 libboost-serialization-dev libboost-stacktrace-dev
  libboost-stacktrace1.71-dev libboost-stacktrace1.71.0 libboost-test-dev libboost-test1.71-dev libboost-test1.71.0 libboost-timer-dev libboost-timer1.71-dev libboost-timer1.71.0 libboost-tools-dev
  libboost-type-erasure-dev libboost-type-erasure1.71-dev libboost-type-erasure1.71.0 libboost-wave-dev libboost-wave1.71-dev libboost-wave1.71.0 libboost1.71-tools-dev libbsd0 libcaf-openmpi-3 libcairo2
  libcbor0.6 libcdt5 libcgraph6 libcoarrays-dev libcoarrays-openmpi-dev libdatrie1 libedit2 libevent-2.1-7 libevent-core-2.1-7 libevent-dev libevent-extra-2.1-7 libevent-openssl-2.1-7 libevent-pthreads-2.1-7
  libfabric1 libfido2-1 libfontconfig1 libfreetype6 libfribidi0 libgcc-8-dev libgd3 libgfortran-8-dev libgfortran-9-dev libgraphite2-3 libgts-0.7-5 libgts-bin libgvc6 libgvpr2 libharfbuzz0b libhwloc-dev
  libhwloc-plugins libhwloc15 libibverbs-dev libibverbs1 libice6 libjbig0 libjpeg-turbo8 libjpeg8 liblab-gamut1 libltdl-dev libnl-3-200 libnl-3-dev libnl-route-3-200 libnl-route-3-dev libnuma-dev libnuma1
  libopenmpi-dev libopenmpi3 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpathplan4 libpciaccess0 libpixman-1-0 libpmix2 libpng16-16 libpsm-infinipath1 libpsm2-2 librdmacm1 libsigsegv2 libsm6
  libthai-data libthai0 libtiff5 libtool libwebp6 libx11-6 libx11-data libxau6 libxaw7 libxcb-render0 libxcb-shm0 libxcb1 libxdmcp6 libxext6 libxmu6 libxmuu1 libxnvctrl0 libxpm4 libxrender1 libxt6 m4
  mpi-default-bin mpi-default-dev ocl-icd-libopencl1 openmpi-bin openmpi-common openssh-client ros-noetic-actionlib ros-noetic-tf ros-noetic-tf2 ros-noetic-tf2-py ros-noetic-tf2-ros ucf x11-common xauth
Suggested packages:
  autoconf-archive gnu-standards autoconf-doc gettext gcc-8-locales gcc-8-multilib gcc-8-doc gfortran-multilib gfortran-doc gfortran-8-multilib gfortran-8-doc gfortran-9-multilib gfortran-9-doc gsfonts
  graphviz-doc libboost1.71-doc gccxml xsltproc doxygen docbook-xml docbook-xsl default-jdk fop libgd-tools libhwloc-contrib-plugins libtool-doc openmpi-doc pciutils gcj-jdk m4-doc opencl-icd keychain
  libpam-ssh monkeysphere ssh-askpass
The following NEW packages will be installed:
  autoconf automake autotools-dev cpp-8 fontconfig fontconfig-config fonts-dejavu-core fonts-liberation gcc-8 gfortran gfortran-8 gfortran-9 graphviz ibverbs-providers libann0 libboost-all-dev
  libboost-atomic-dev libboost-container-dev libboost-container1.71-dev libboost-container1.71.0 libboost-context-dev libboost-context1.71-dev libboost-context1.71.0 libboost-coroutine-dev
  libboost-coroutine1.71-dev libboost-coroutine1.71.0 libboost-exception-dev libboost-exception1.71-dev libboost-fiber-dev libboost-fiber1.71-dev libboost-fiber1.71.0 libboost-graph-dev
  libboost-graph-parallel-dev libboost-graph-parallel1.71-dev libboost-graph-parallel1.71.0 libboost-graph1.71-dev libboost-graph1.71.0 libboost-iostreams-dev libboost-iostreams1.71-dev
  libboost-iostreams1.71.0 libboost-locale-dev libboost-locale1.71-dev libboost-locale1.71.0 libboost-log-dev libboost-log1.71-dev libboost-log1.71.0 libboost-math-dev libboost-math1.71-dev libboost-math1.71.0
  libboost-mpi-dev libboost-mpi-python-dev libboost-mpi-python1.71-dev libboost-mpi-python1.71.0 libboost-mpi1.71-dev libboost-mpi1.71.0 libboost-numpy-dev libboost-numpy1.71-dev libboost-numpy1.71.0
  libboost-python-dev libboost-python1.71-dev libboost-python1.71.0 libboost-random-dev libboost-random1.71-dev libboost-random1.71.0 libboost-serialization-dev libboost-stacktrace-dev
  libboost-stacktrace1.71-dev libboost-stacktrace1.71.0 libboost-test-dev libboost-test1.71-dev libboost-test1.71.0 libboost-timer-dev libboost-timer1.71-dev libboost-timer1.71.0 libboost-tools-dev
  libboost-type-erasure-dev libboost-type-erasure1.71-dev libboost-type-erasure1.71.0 libboost-wave-dev libboost-wave1.71-dev libboost-wave1.71.0 libboost1.71-tools-dev libbsd0 libcaf-openmpi-3 libcairo2
  libcbor0.6 libcdt5 libcgraph6 libcoarrays-dev libcoarrays-openmpi-dev libdatrie1 libedit2 libevent-2.1-7 libevent-core-2.1-7 libevent-dev libevent-extra-2.1-7 libevent-openssl-2.1-7 libevent-pthreads-2.1-7
  libfabric1 libfido2-1 libfontconfig1 libfreetype6 libfribidi0 libgcc-8-dev libgd3 libgfortran-8-dev libgfortran-9-dev libgraphite2-3 libgts-0.7-5 libgts-bin libgvc6 libgvpr2 libharfbuzz0b libhwloc-dev
  libhwloc-plugins libhwloc15 libibverbs-dev libibverbs1 libice6 libjbig0 libjpeg-turbo8 libjpeg8 liblab-gamut1 libltdl-dev libnl-3-200 libnl-3-dev libnl-route-3-200 libnl-route-3-dev libnuma-dev libnuma1
  libopenmpi-dev libopenmpi3 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpathplan4 libpciaccess0 libpixman-1-0 libpmix2 libpng16-16 libpsm-infinipath1 libpsm2-2 librdmacm1 libsigsegv2 libsm6
  libthai-data libthai0 libtiff5 libtool libwebp6 libx11-6 libx11-data libxau6 libxaw7 libxcb-render0 libxcb-shm0 libxcb1 libxdmcp6 libxext6 libxmu6 libxmuu1 libxnvctrl0 libxpm4 libxrender1 libxt6 m4
  mpi-default-bin mpi-default-dev ocl-icd-libopencl1 openmpi-bin openmpi-common openssh-client ros-foxy-ros1-bridge ros-noetic-actionlib ros-noetic-tf ros-noetic-tf2 ros-noetic-tf2-py ros-noetic-tf2-ros ucf
  x11-common xauth
0 upgraded, 181 newly installed, 0 to remove and 0 not upgraded.
Need to get 75.5 MB of archives.
After this operation, 380 MB of additional disk space will be used.
```

**Comment by mjcarroll** [comment]
@mikaelarguedas Would it be better to trim the dependencies of `actionlib` ? Or just revert this altogether?

**Comment by mikaelarguedas** [comment]
Trimming the dependencies in actionlib and the rest of `ros_base` would be awesome as it will allow to reduce significantly the footprint of the default ros install (and docker images). So regardless of this :100: for trimming libboost-all-dev from low level packages

I'm ambivalent about reverting this. This was added for eloquent/dashing because people were requesting it, so if the impact of keeping this is small (once dependencies trimmed) it would be useful to some users to keep it. On the other hand, `tf` being deprecated for a long time in ROS1, people targeting noetic and using the bridge to migrate to ROS 2 should really start by migrating to tf2 so it may be fine to revert this for Foxy.

**Pull request merged**
